Enable all new Rubocop cops by default
Rubocop version `0.84.0` appears to be broken, with:
```
MethodError: undefined method `join' for #<Set: {:==, :===, :!=, :<=, :>=, :>, :<}>
```
So we froze it at version `0.83.0`.

Co-authored-by: Mathias Jean Johansen <mj@abtion.com>